# Generated by Django 2.1.2 on 2018-10-05 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dojo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400, verbose_name='Dojo name')),
                ('address', models.CharField(blank=True, max_length=400, null=True, verbose_name='Address')),
                ('number', models.CharField(blank=True, max_length=10, null=True, verbose_name='Number')),
                ('postal_code', models.IntegerField(blank=True, null=True, verbose_name='Postal code')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='City')),
                ('open_date', models.DateField(verbose_name='Open date')),
            ],
        ),
    ]
