# Generated by Django 2.1.2 on 2018-10-05 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deshi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('surname', models.CharField(max_length=255, verbose_name='Name')),
                ('birth_day', models.DateField(blank=True, null=True, verbose_name='Birth day')),
                ('tel', models.CharField(blank=True, max_length=255, null=True, verbose_name='Phone number')),
                ('mobile', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mobile number')),
                ('dojo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dojo.Dojo')),
            ],
        ),
    ]
