# Generated by Django 2.1.2 on 2018-10-08 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0002_deshi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Levels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=255, verbose_name='Level')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Shiken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('place', models.CharField(max_length=255, verbose_name='Place')),
                ('deshi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dojo.Deshi')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dojo.Levels')),
            ],
        ),
    ]
