# Generated by Django 2.1.2 on 2018-10-08 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0003_levels_shiken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deshi',
            name='surname',
            field=models.CharField(max_length=255, verbose_name='Surname'),
        ),
    ]
