# Generated by Django 2.1.2 on 2018-10-11 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kyokai', '0002_affiliation_price'),
        ('dojo', '0004_auto_20181008_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiken',
            name='kyokai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kyokai.Kyokai'),
        ),
    ]
