# Generated by Django 2.1.2 on 2018-11-12 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0005_shiken_kyokai'),
    ]

    operations = [
        migrations.AddField(
            model_name='deshi',
            name='birth_place',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Birth place'),
        ),
        migrations.AddField(
            model_name='deshi',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='deshi',
            name='fiscal_code',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Fiscal code'),
        ),
        migrations.AddField(
            model_name='deshi',
            name='postal_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Postal code'),
        ),
        migrations.AddField(
            model_name='deshi',
            name='residence_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Residence street'),
        ),
        migrations.AddField(
            model_name='deshi',
            name='residence_place',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Residence place'),
        ),
        migrations.AddField(
            model_name='deshi',
            name='residence_province',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Residence province'),
        ),
        migrations.AddField(
            model_name='deshi',
            name='residence_street',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Residence street'),
        ),
    ]
